[[platform-integration-reference]]

= Platform Integration

:toc:

== Preface

include::preface.adoc[]

== Introduction

This first part of the reference documentation is a high-level overview of Platform Integration and the underlying
concepts and some code snippets that will get you up and running as quickly as possible.

include::quick-tour.adoc[]

== Platform Kafka Integration

This part of the reference shows how to use the `platform-integration-kafka` module of Platform Integration.

include::kafka-integration.adoc[]

== Platform Neo4j Integration

This part of the reference shows how to use the `platform-integration-neo4j` module of Platform Integration.

include::neo4j-integration.adoc[]

== Testing
This part of the reference shows how to test the application.
include::testing.adoc[]

== Reference

This part of the reference documentation details the various components that comprise Platform Integration.
The <<integration,main chapter>> covers the core classes to develop a Integration application with Platform.
include::spring-kafka.adoc[]

[[resources]]
== Other Resources

In addition to this reference documentation, there exist a number of other resources that may help you learn about
Platform Integration.

[appendix]
include::appendix.adoc[]
