/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hmangala' at '3/8/16 3:28 PM' with Gradle 2.14
 *
 * @author hmangala, @date 3/8/16 3:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
